### ISSUE TITLE
block的 linked reference 只显示块引用，不显示块嵌入

### ISSUE THREAD

**Issue by EasonSpirit** [logseq/db-test-cn#11]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

如题

### Reproduce the Bug

1. 在任意#tag页面 的table中 直接新增一个node，并记录名字；
![image](https://github.com/user-attachments/assets/0284fb60-3bec-403c-8dfa-5096809a4c14)
 
2. 在另一个页面里，对该node进行引用、然后再另起一行，进行嵌入；
![image](https://github.com/user-attachments/assets/4a0d4f2b-0b9a-4bcc-bed1-512ece75acd1)

3. 可以发现，在页面的原始node里，引用数量已变成了2，，但是下面的linked reference只显示块引用的内容，而没有块嵌入的内容
![image](https://github.com/user-attachments/assets/f2ab569a-1717-4a90-ad6f-b2cced834409)

### Expected Behavior

角标的数字，应该与linked reference显示的数量一致；也就是说，linked reference也应该显示块嵌入的内容

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
fixed.
