### ISSUE TITLE
[[]]进行页面引用时，若有Tags和pages的同名页面，不论选哪一个，均只会链接到其中之一（目前貌似Tags优先）

### ISSUE THREAD

**Issue by EasonSpirit** [logseq/db-test-cn#12]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

如题

### Reproduce the Bug

1. 创建一个Tag 类型的 #知识；
2. 创建一个page 类型 [[知识]]；
3. 在任意一个页面中，输入[[]]，见图：
<img width="89" alt="5108933165258826d69b7ac4e6b58e1" src="https://github.com/user-attachments/assets/00794c54-e72d-4c80-98c2-c3f0a3b14e44">

4. 然后不论选择任意一个，均链接至Tag 类型的 #知识

### Expected Behavior

应该按照用户选择的页面，正确链接至对应的页面

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
这个 bug 还能复现吗？我这边复现不了。

**Comment by EasonSpirit** [comment]
> 这个 bug 还能复现吗？我这边复现不了。

用我之前给你的 库 试试呢

**Comment by EasonSpirit** [comment]
[logseq_db_DB Demo_1723432226.zip](https://github.com/user-attachments/files/16577057/logseq_db_DB.Demo_1723432226.zip)
我导出了一份最新的，日志页面已经打上了两行，应该可以看到两个的预览都是同一个页面

**Comment by tiensonqin** [comment]
fixed
