### ISSUE TITLE
自带的 三个标签页（Root Tag、Task、Card）增加 Tag property  后无法删除和隐藏

### ISSUE THREAD

**Issue by langyamu** [logseq/db-test-cn#13]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

https://github.com/user-attachments/assets/8deca11f-6327-4dd5-ba3d-f0c9dad7788a

### Reproduce the Bug

见上方视频

### Screenshots

因为这里的 Tag property 可能属于 系统自有属性的 概念（自我理解），
对于预设的 Root Tag、Task、Card 而言，
本应有的 Tag property （如 Task 自带的 Status 属性），可能需要 限制不可删除 或者 可以修改
后面用户新增的 Tag property  应该是可以修改或删除的

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Fixed by https://github.com/logseq/logseq/commit/c7c17e3dd279b2f9649092db3033a4c81f899888.
