### ISSUE TITLE
x掉一个node的tag，UI没有正确更新

### ISSUE THREAD

**Issue by dale502** [logseq/db-test-cn#14]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

如果一个node加了多个tag，x掉一个tag，实际上是删掉了，UI显示的剩下的tag错误。
这也导致无法把一个node的多个tag全都x掉

### Reproduce the Bug

1.node加多个tag
2.x掉其中一个tag

### Screenshots

<img width="952" alt="image" src="https://github.com/user-attachments/assets/92cb0a01-3877-4b20-87a7-5c4704c3585f">

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Fixed.
