### ISSUE TITLE
之前db版本的sqlite数据，迁移到最新，在加tag时会重复显示

### ISSUE THREAD

**Issue by dale502** [logseq/db-test-cn#15]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

一个旧db库，迁移到最新，加tag会显示2遍，点哪个没区别。
新建db库，没法复现。
附上一个sqlite备份，你导入看看
https://coffee502.notion.site/2024-08-11-15-21-17-9c2bab53d21040db9ebd95739d6a2968?pvs=4

### Reproduce the Bug

1.导入
2.加tag，会显示重复项

### Screenshots

<img width="242" alt="image" src="https://github.com/user-attachments/assets/94226c54-c40b-4a3e-ba94-d7528cf22764">

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by RCmerci** [comment]
在 test.logseq.com 上用你提供的graph测试了一次，没复现出来。需要什么具体操作吗？
我的步骤是：
1. 导入sqlitedb
2. cmd+k 搜索“12”，没出现你截图的样子
3. 创建新的block，输入#t20
4. cmd+k 搜索“20”，也没出现多个#t20

**Comment by dale502** [comment]
>创建新的block，输入#t20

你是测t12还是t20 ? 我的这个库里没有关于20的
应该测 `#12`

**Comment by dale502** [comment]
<img width="890" alt="image" src="https://github.com/user-attachments/assets/9ff49876-258a-49f8-9782-b09b3df92188">
如图，我这还是可以复现

**Comment by RCmerci** [comment]
可以复现，之前在cmd+k搜索里搜“12”，应该是用#搜来复现

**Comment by tiensonqin** [comment]
Fixed by https://github.com/logseq/logseq/commit/c59fac647f44c31fd8506a7cabb2b3233a64b319.
