### ISSUE TITLE
引用的block中如果含有inline页面，会显示ID，而不是内容

### ISSUE THREAD

**Issue by shijiafodizi** [logseq/db-test-cn#17]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

如题，
![image](https://github.com/user-attachments/assets/aeb2f3da-5e11-4744-a25e-8b1a40f7d7d2)

### Reproduce the Bug

第一次没有问题，我稍微修改了盒子里面的一些内容，inline页面也改了一个字，就出现了上图的现象。

[logseq_db_Demo_1723638709.zip](https://github.com/user-attachments/files/16613000/logseq_db_Demo_1723638709.zip)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
fixed.
