### ISSUE TITLE
导出的.sqlite文件没有包含assets资产

### ISSUE THREAD

**Issue by kx1356** [logseq/db-test-cn#19]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

笔记内容中包含图片，视频与pdf等文件，迁移时导出格式为.sqlite文件中未包含这些资产。

### Reproduce the Bug

笔记内容中包含图片，视频与pdf等文件，迁移时导出格式为.sqlite文件中未包含这些资产。

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by RCmerci** [comment]
db版本的assets的导出，管理等等，还在实现中

**Comment by tiensonqin** [comment]
assets 导出已经支持。
