### ISSUE TITLE
tag 下的 node显示，[[]]里面只显示了id，而不是内容

### ISSUE THREAD

**Issue by hillsmao** [logseq/db-test-cn#2]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

![image](https://github.com/user-attachments/assets/832cfdda-2892-4acd-bcdf-2d8ad471a70f)

### Reproduce the Bug

如图

无论是 [[page]]  还是 [[块引用]] ，都不显示内容

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
@hillsmao 再试试看看

**Comment by hillsmao** [comment]
可以了，非常酷
