### ISSUE TITLE
SQLiteDB 错误: No protocol method INode.node-len defined for type null

### ISSUE THREAD

**Issue by xyhp915** [logseq/db-test-cn#21]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

![62691724144325_ pic](https://github.com/user-attachments/assets/12ac0bec-084d-4e7a-be1b-c0fcfc008b67)

### Reproduce the Bug

Contact Wechat user.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
fixed.
