### ISSUE TITLE
task node不能同名

### ISSUE THREAD

**Issue by dale502** [logseq/db-test-cn#26]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

![WechatIMG593](https://github.com/user-attachments/assets/1ce1e9c9-7de4-45eb-aa22-6f1366ced4a3)

### Reproduce the Bug

- 输入1，`cmd+回车`，变成task
- 再输入1，`cmd+回车`，变成task
第二个1就会报错，无法保存

**Comment by tiensonqin** [comment]
Fixed now.
