### ISSUE TITLE
Task中的 Parent 属性无法删除

### ISSUE THREAD

**Issue by ZangXincz** [logseq/db-test-cn#27]
### Search first

- [ ] I searched and no similar issues were found

### What Happened?

无法删除Task中的Parent属性
![image](https://github.com/user-attachments/assets/f64e755e-9658-42a0-a13a-2ee8444e4cda)

导致其他页面所有添加的task都会相似Parent属性
![image](https://github.com/user-attachments/assets/60033bd5-472c-46d5-aecf-0d4b20515238)

### Reproduce the Bug

1. 添加Parent属性

### Expected Behavior

可以删除Parent属性
或者在非Task处的任务下不显示 Parent属性
![image](https://github.com/user-attachments/assets/d1ae2129-a162-424e-bc66-7f6cd9824cb7)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
@qingyuncz Hi. I saw this bug affected any tag. A pushed a fix which will be available on https://test.logseq.com/ in 10 minutes

**Comment by logseq-cldwalker** [comment]
Closing as this should be fixed but feel free to comment if it's not
