### ISSUE TITLE
【产品建议】Property 的 Specify node tags 限定一个tag的时候，可选范围不仅是打了该tag的内容，同时还有该tag的子tag

### ISSUE THREAD

**Issue by EasonSpirit** [logseq/db-test-cn#34]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

如图：
<img width="924" alt="微信图片_20241028174106" src="https://github.com/user-attachments/assets/30a0ca45-d53d-409d-97d1-241683299735">
目前在Specify node tags 限定 #知识 时，仅可选择打了 #知识 的node，希望也可以新增一种场景：
当我限定了 #知识 时，该property仅可选择 #知识 的子tag/子子tag，如图，即为 #第二语言

### Reproduce the Bug

同上

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
最新的版本已经支持。
