### ISSUE TITLE
DB版本如何使用块别名功能？

### ISSUE THREAD

**Issue by EasonSpirit** [logseq/db-test-cn#35]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

在MD版本中，我们可以通过如下形式控制一个嵌入/引用的块的显示名称：
`[显示名称](((block的id)))` 此时，离开编辑模式，展示的就是 `显示名称`

在DB版本中，所有的引用语法一致，均为[[]]
但是如上的用法却不复存在了，如图：
<img width="292" alt="af1a64bd4bc6a8a170742e901df088b" src="https://github.com/user-attachments/assets/2397ee54-7b5c-426b-ba13-2d40289a08df">
<img width="115" alt="6236a4e32b8c0efe098a7e75d4e764f" src="https://github.com/user-attachments/assets/823dcf88-b82b-442d-a8ad-e2f9412cd921">
可以看到，并不会显示11

### Reproduce the Bug

我有两种想法：
1. 使用MD版本类似的方案：`[显示名称]([[block的id]])` ：更灵活；
2. 给block加上 alias 属性：设置的属性值，可以在搜索时直接搜到并使用：更符合一致性原理，与page的别名一致。

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
已支持
