### ISSUE TITLE
node添加的deadline，然后删除date，deadline页面还会留下linked ref

### ISSUE THREAD

**Issue by dale502** [logseq/db-test-cn#36]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

一个node添加的deadline，然后删除date，deadline页面还会留下linked ref

### Reproduce the Bug

![Xnip2024-11-14_11-18-49](https://github.com/user-attachments/assets/cf394817-e465-4a09-b02a-db495e25ecce)
![Xnip2024-11-14_11-20-09](https://github.com/user-attachments/assets/134efa62-db9e-45a3-8223-812b0a5198ac)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. Thanks for the report. A fix for this should be up on https://test.logseq.com/ in 10 minutes

**Comment by dale502** [comment]
fixed👍🏻
