### ISSUE TITLE
block 搜索长度必须 > 2

### ISSUE THREAD

**Issue by shijiafodizi** [logseq/db-test-cn#5]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

1，采用(())搜索block时，搜索的内容很有限。
2，设置property为node，如果敲入两个字符，只能搜索到页面，不能搜索到block。
排版问题：
3，设置property为node，如果敲入两个以上字符，可以正常搜索到block，比1要好。但结果呈现长长的一行，不方便看。希望排版是这样的：1，优先显示之前选择过的node，2，分页面，block等板块进行选择，类似老版本的search 3，block的显示类比老版本。
4，设置property为node，选择的是block时在表格中会显得太长，希望有缩略模式。

### Reproduce the Bug

略

### Screenshots

![1722947106933](https://github.com/user-attachments/assets/db31016e-ee0e-4705-94e0-caf3564b366f)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by cordinGH** [comment]
@tiensonqin 您好，这个问题已经存在3个月了，不知道为什么迟迟不修复，这真的非常影响中文用户的使用体验。

不仅是(())存在这个问题，是所有的搜索相关功能都存在。

**Comment by tiensonqin** [comment]
Fixed.
