### ISSUE TITLE
复制粘贴整块时，页面需要刷新才能展示，且部分前端渲染丢失

### ISSUE THREAD

**Issue by EasonSpirit** [logseq/db-test-cn#7]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

整块复制粘贴block后，需要刷新页面才能看到粘贴后的block的内容
且H1~H5的页面渲染失效

### Reproduce the Bug

具体操作看录屏

https://github.com/user-attachments/assets/f74cff40-1012-4f47-a22a-75178968444f

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
@EasonSpirit 这个 graph 方便上传下或者发我邮箱吗？我怀疑是跟长页面 lazy load 有关，但是我本地没复现出来。

**Comment by EasonSpirit** [comment]
> @EasonSpirit 这个 graph 方便上传下或者发我邮箱吗？我怀疑是跟长页面 lazy load 有关，但是我本地没复现出来。
[logseq_db_DB Demo_1723104803.zip](https://github.com/user-attachments/files/16539908/logseq_db_DB.Demo_1723104803.zip)

**Comment by tiensonqin** [comment]
@EasonSpirit 大概10分钟后试试看。

**Comment by EasonSpirit** [comment]
已修复
