### ISSUE TITLE
"全部页面"中tag类型悬停显示不一致

### ISSUE THREAD

**Issue by iiweixiao** [logseq/db-test-cn#8]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

"全部页面"中，同样是Tag类型，“软件”和“工具”的悬停显示效果不一样

https://github.com/user-attachments/assets/cb50d256-fa6c-4285-ac65-249b7493a7bc

### Reproduce the Bug

找到原因了，因为“工具”同时有Tag和Page类型。

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
fixed
